# Generated by Django 4.1.2 on 2022-10-23 11:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookinfo',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
